include $(TOPDIR)/rules.mk

LUCI_TITLE:=Device Manager
LUCI_DEPENDS:=+luci-base

PKG_VERSION:=0.1.0
PKG_RELEASE:=1
PKG_MAINTAINER:=TurboWrt
PKG_LICENSE:=MIT
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
